name: powerbank_app
description: A Flutter app for quick power bank rental according to provided technical specification and UI.
publish_to: "none"

version: 1.0.0+1
environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  url_launcher: ^6.3.0
  flutter_braintree: ^4.0.0
  cupertino_icons: ^1.0.8
  responsive_sizer: ^3.3.1
  google_fonts: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
